[package]
name = "bepinex-updater"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = "0.15.0"
reqwest = { version = "0.11.3", features = ["stream"] }
futures-util = "0.3.14"

tokio = { version = "1", features = ["full"] }
zip-extract = "0.1.2"
regex = "1.10.2"
